services:
  edutrack-backend:
    image: edutrack-backend:v1
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env.compose
    ports:
      - "8002:8002"
    command: uvicorn main:app --host 0.0.0.0 --port 8002 --reload
    depends_on:
      db_service:
        condition: service_healthy
    volumes:
      - ./src:/code:rw
    develop:
     watch:
      - action: rebuild
        path: Dockerfile
      - action: rebuild
        path: requirements.txt
      - action: rebuild
        path: compose.yaml
  db_service:
    image: timescale/timescaledb:latest-pg17
    environment:
      - POSTGRES_USER=time-user
      - POSTGRES_PASSWORD=time-pw
      - POSTGRES_DB=timescaledb
    ports:
      - "5432:5432"
    expose:
      - 5432
    volumes:
      - timescaledb_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U time-user -d timescaledb"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  timescaledb_data: