services:
  edutrack-frontend:
    image: edutrack-frontend:v1
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./src:/app/src:rw
      - ./index.html:/app/index.html:rw
      - ./vite.config.ts:/app/vite.config.ts:rw
    develop:
      watch:
        - action: rebuild
          path: Dockerfile
        - action: rebuild
          path: package.json
